### ISSUE TITLE
Do you have an example of running tests using Pascal in a GitHub Action?

### ISSUE THREAD

**Issue by cclauss** [DeveloppeurPascal/_AllProjects#13]
I have created automated tests for numerous languages but never for Pascal. It might be an interesting challenge.

Would it be of interest to have a Pascal repo run automated tests when code is changed?
* Like: https://github.com/pyodide/pyodide/actions
* This free Pascal workflow suggests that it would be possible:
    * https://github.com/exercism/free-pascal/blob/main/.github/workflows/test.yml

The use of GitHub Actions is free of charge for public repos... https://github.com/features/actions

**Comment by DeveloppeurPascal** [comment]
I never used GitHub Actions, but I know it's possible to automate some things for Pascal language. The problem is the compilers.
If you use Delphi, GitHub Actions must have access to a Delphi compiler with a license. Embarcadero is working on the subject. Some solutions are available for continuous integration. you can check on YouTube to see some implementations.
If you code in FreePascal, it's easier because the compilers can be used for free.

**Comment by cclauss** [comment]
Merci.  What might be useful is to start with a simple Pascal codebase that has at least one test.  I could get a GitHub Action testing that with FreePascal. Then when Embarcadero has an approach, we could swap out `fpc` for the Delphi compiler.

Do you have a simple codebase that I could start with?

**Comment by cclauss** [comment]
Something like this...

Test results: https://github.com/exercism/free-pascal/pull/21/checks?check_run_id=23603820352

**Comment by cclauss** [comment]
Closing https://github.com/exercism/free-pascal/runs/23713278068
